Close Modal Button
tobyakin/MySpurr-App pull request #42
Opened 2024-08-19 21:17 UTC by Deen-Abdultawab

This is the commit for close modal functionality on the job post options modal

2024-08-25 23:57 UTC, Deen-Abdultawab commented
Commit for Job Payment Integration

2024-08-26 18:40 UTC, onyiimesi requested changes

2024-08-26 18:40 UTC, onyiimesi commented on src/stores/jobs.js
>        is_highlighted: is_highlighted,
Remove is_highlighted from the payload

2024-08-26 18:40 UTC, onyiimesi commented on src/components/ui/Jobs/ReviewJob.vue
> +        console.log(showModal)
Remove console.log

2024-08-26 19:37 UTC, merged